=== boruroad/Estructuras-de-Datos-2021-1/Prácticas/P7/elementos.dtd
<!--
Archivo de descripción para la tabla periódica archivo XML.
Author: Adrián Bonilla Ruiz
Num. Cta. 31721903-8
Version: 1.0 2020
-->

<!ELEMENT tabla (#PCDATA) >
<!ELEMENT elemento (#PCDATA) >


<!ATTLIST elemento nombre  CDATA #REQUIRED >
<!ATTLIST elemento simbolo CDATA #REQUIRED >
<!ATTLIST elemento numero  CDATA #REQUIRED >
<!ATTLIST elemento masa    CDATA #REQUIRED >

=== boruroad/Estructuras-de-Datos-2021-1/Prácticas/P7/tabla-periodica.xml
<?xml version="1.0" ?>
<!DOCTYPE tabla SYSTEM "elementos.dtd"  >
<tabla >
	<elemento nombre = "hidrógeno"    simbolo="H"   numero="1"   masa="1.00794"    />
	<elemento nombre = "helio"	      simbolo="He"  numero="2"   masa="4.0026"     />
	<elemento nombre = "litio"        simbolo="Li"  numero="3"   masa="6.94174064" />
	<elemento nombre = "berilio"      simbolo="Be"  numero="4"   masa="9.0122"     />
	<elemento nombre = "boro"         simbolo="B"   numero="5"   masa="10.811"     />
	<elemento nombre = "carbono"      simbolo="C"   numero="6"   masa="12.0107"    />
	<elemento nombre = "nitrógeno"    simbolo="N"   numero="7"   masa="14.0067"    />
	<elemento nombre = "oxígeno"      simbolo="O"   numero="8"   masa="15.9994"    />
	<elemento nombre = "flúor"        simbolo="F"   numero="9"   masa="18.9984032" />
	<elemento nombre = "neón"         simbolo="Ne"  numero="10"  masa="20.1797"    />
	<elemento nombre = "sodio"        simbolo="Na"  numero="11"  masa="22.98976928"/>
	<elemento nombre = "magnesio"     simbolo="Mg"  numero="12"  masa="24.31"      />
	<elemento nombre = "aluminio"     simbolo="Al"  numero="13"  masa="26.9815386" />
	<elemento nombre = "silicio"      simbolo="Si"  numero="14"  masa="28.085"     />
	<elemento nombre = "fósforo"      simbolo="P"   numero="15"  masa="30.9737620" />
	<elemento nombre = "azufre"       simbolo="S"   numero="16"  masa="32.065"     />
	<elemento nombre = "cloro"        simbolo="Cl"  numero="17"  masa="35.453"     />
	<elemento nombre = "argón"        simbolo="Ar"  numero="18"  masa="39.948"     />
	<elemento nombre = "potasio"      simbolo="K"   numero="19"  masa="39.0983"    />
	<elemento nombre = "calcio"       simbolo="Ca"  numero="20"  masa="40.078"     />
	<elemento nombre = "escandio"     simbolo="Sc"  numero="21"  masa="44.955910"  />
	<elemento nombre = "titanio"      simbolo="Ti"  numero="22"  masa="47.867"     />
	<elemento nombre = "vanadio"      simbolo="V"   numero="23"  masa="50.9415"    />
	<elemento nombre = "cromo"        simbolo="Cr"  numero="24"  masa="51.9961"    />
	<elemento nombre = "manganeso"    simbolo="Mn"  numero="25"  masa="54.938049"  />
	<elemento nombre = "hierro"       simbolo="Fe"  numero="26"  masa="55.845"     />
	<elemento nombre = "cobalto"      simbolo="Co"  numero="27"  masa="58.9332"    />
	<elemento nombre = "níquel"       simbolo="Ni"  numero="28"  masa="58.71"      />
	<elemento nombre = "cobre"        simbolo="Cu"  numero="29"  masa="63.536"     />
	<elemento nombre = "zinc"         simbolo="Zn"  numero="30"  masa="65.409"     />
	<elemento nombre = "galio"        simbolo="Ga"  numero="31"  masa="69.723"     />
	<elemento nombre = "germanio"     simbolo="Ge"  numero="32"  masa="72.64"      />
	<elemento nombre = "arsénico"     simbolo="As"  numero="33"  masa="74.9216"    />
	<elemento nombre = "selenio"      simbolo="Se"  numero="34"  masa="78.96"      />
	<elemento nombre = "bromo"        simbolo="Br"  numero="35"  masa="79.904"     />
	<elemento nombre = "kriptón"      simbolo="Kr"  numero="36"  masa="83.798"     />
	<elemento nombre = "rubidio"      simbolo="Rb"  numero="37"  masa="85.4678"    />
	<elemento nombre = "estroncio"    simbolo="Sr"  numero="38"  masa="87.62"      />
	<elemento nombre = "itrio"        simbolo="Y"   numero="39"  masa="88.90585"   />
	<elemento nombre = "circonio"     simbolo="Zr"  numero="40"  masa="91.224"     />
	<elemento nombre = "niobio"       simbolo="Nb"  numero="41"  masa="92.90638"   />
	<elemento nombre = "molibdeno"    simbolo="Mo"  numero="42"  masa="95.94"      />
	<elemento nombre = "tecnecio"     simbolo="Tc"  numero="43"  masa="98.9093"    />
	<elemento nombre = "rutenio"      simbolo="Ru"  numero="44"  masa="101.07"     />
	<elemento nombre = "rodio"        simbolo="Rh"  numero="45"  masa="102.9055"   />
	<elemento nombre = "paladio"      simbolo="Pd"  numero="46"  masa="106.42"     />
	<elemento nombre = "plata"        simbolo="Ag"  numero="47"  masa="107.8683"   />
	<elemento nombre = "cadmio"       simbolo="Cd"  numero="48"  masa="112.411"    />
	<elemento nombre = "indio"        simbolo="In"  numero="49"  masa="114.818"    />
	<elemento nombre = "estaño"       simbolo="Sn"  numero="50"  masa="118.710"    />
	<elemento nombre = "antimonio"    simbolo="Sb"  numero="51"  masa="121.76"     />
	<elemento nombre = "telurio"      simbolo="Te"  numero="52"  masa="127.6"      />
	<elemento nombre = "yodo"         simbolo="I"   numero="53"  masa="126.90447"  />
	<elemento nombre = "xenón"        simbolo="Xe"  numero="54"  masa="131.293"    />
	<elemento nombre = "cesio"        simbolo="Cs"  numero="55"  masa="132.90545"  />
	<elemento nombre = "bario"        simbolo="Ba"  numero="56"  masa="137.327"    />
	<elemento nombre = "lantano"      simbolo="La"  numero="57"  masa="138.9055"   />
	<elemento nombre = "cerio"        simbolo="Ce"  numero="58"  masa="140.116"    />
	<elemento nombre = "praseodimio"  simbolo="Pr"  numero="59"  masa="140.90765"  />
	<elemento nombre = "neodimio"     simbolo="Nd"  numero="60"  masa="144.24"     />
	<elemento nombre = "prometio"     simbolo="Pm"  numero="61"  masa="145"        />
	<elemento nombre = "samario"      simbolo="Sm"  numero="62"  masa="150.35"     />
	<elemento nombre = "europio"      simbolo="Eu"  numero="63"  masa="151.964"    />
	<elemento nombre = "gadolinio"    simbolo="Gd"  numero="64"  masa="157.25"     />
	<elemento nombre = "terbio"       simbolo="Tb"  numero="65"  masa="158.92534"  />
	<elemento nombre = "disprosio"    simbolo="Dy"  numero="66"  masa="162.5"      />
	<elemento nombre = "holmio"       simbolo="Ho"  numero="67"  masa="164.9303"   />
	<elemento nombre = "erbio"        simbolo="Er"  numero="68"  masa="167.259"    />
	<elemento nombre = "tulio"        simbolo="Tm"  numero="69"  masa="168.934"    />
	<elemento nombre = "iterbio"      simbolo="Yb"  numero="70"  masa="173.04"     />
	<elemento nombre = "lutencio"     simbolo="Lu"  numero="71"  masa="174.967"    />
	<elemento nombre = "hafnio"       simbolo="Hf"  numero="72"  masa="178.49"     />
	<elemento nombre = "tantalio"     simbolo="Ta"  numero="73"  masa="180.9479"   />
	<elemento nombre = "wolframio"    simbolo="W"   numero="74"  masa="183.84"     />
	<elemento nombre = "renio"        simbolo="Re"  numero="75"  masa="186.207"    />
	<elemento nombre = "osmio"        simbolo="Os"  numero="76"  masa="190.23"     />
	<elemento nombre = "iridio"       simbolo="Ir"  numero="77"  masa="192.217"    />
	<elemento nombre = "platino"      simbolo="Pt"  numero="78"  masa="195.084"    />
	<elemento nombre = "oro"          simbolo="Au"  numero="79"  masa="196.966569" />
	<elemento nombre = "mercurio"     simbolo="Hg"  numero="80"  masa="200.59"     />
	<elemento nombre = "talio"        simbolo="Tl"  numero="81"  masa="204.3833"   />
	<elemento nombre = "plomo"        simbolo="Pb"  numero="82"  masa="207.2"      />
	<elemento nombre = "bismuto"      simbolo="Bi"  numero="83"  masa="208.98038"  />
	<elemento nombre = "polonio"      simbolo="Po"  numero="84"  masa="209.9824"   />
	<elemento nombre = "astato"       simbolo="At"  numero="85"  masa="210"        />
	<elemento nombre = "radón"        simbolo="Rn"  numero="86"  masa="222"        />
	<elemento nombre = "francio"      simbolo="Fr"  numero="87"  masa="223"        />
	<elemento nombre = "radio"        simbolo="Ra"  numero="88"  masa="226.0254"   />
	<elemento nombre = "actinio"      simbolo="Ac"  numero="89"  masa="227"        />
	<elemento nombre = "torio"        simbolo="Th"  numero="90"  masa="232.0381"   />
	<elemento nombre = "protactinio"  simbolo="Pa"  numero="91"  masa="231.03588"  />
	<elemento nombre = "uranio" 	  simbolo="U"   numero="92"  masa="238.02891"  />
	<elemento nombre = "neptunio"     simbolo="Np"  numero="93"  masa="237"        />
	<elemento nombre = "plutonio" 	  simbolo="Pu"  numero="94"  masa="244"        />
	<elemento nombre = "amercio" 	  simbolo="Am"  numero="95"  masa="243"        />
	<elemento nombre = "curio" 	 	  simbolo="Cm"  numero="96"  masa="247"        />
	<elemento nombre = "berkelio" 	  simbolo="Bk"  numero="97"  masa="247"        />
	<elemento nombre = "californio"   simbolo="Cf"  numero="98"  masa="251"        />
	<elemento nombre = "einstenio" 	  simbolo="Es"  numero="99"  masa="252"        />
	<elemento nombre = "fermio" 	  simbolo="Fm"  numero="100" masa="257"        />
	<elemento nombre = "mendelevio"   simbolo="Md"  numero="101" masa="258"        />
	<elemento nombre = "nobelio"   	  simbolo="No"  numero="102" masa="259"        />
	<elemento nombre = "lawrencio" 	  simbolo="Lr"  numero="103" masa="262"        />
	<elemento nombre = "rutherfordio" simbolo="Rf"  numero="104" masa="261"        />
	<elemento nombre = "dubnio" 	  simbolo="Db"  numero="105" masa="262"        />
	<elemento nombre = "seaborgio" 	  simbolo="Sg"  numero="106" masa="269"        />
	<elemento nombre = "bohrio" 	  simbolo="Bh"  numero="107" masa="264"        />
	<elemento nombre = "hassio" 	  simbolo="Hs"  numero="108" masa="269"        />
	<elemento nombre = "meitnerio" 	  simbolo="Mt"  numero="109" masa="268"        />
	<elemento nombre = "darmstadio"   simbolo="Ds"  numero="110" masa="281"        />
	<elemento nombre = "roentgenio"   simbolo="Rg"  numero="111" masa="281"        />
	<elemento nombre = "copernicio"   simbolo="Cn"  numero="112" masa="285"        />
	<elemento nombre = "ununtrio" 	  simbolo="Uut" numero="113" masa="286"        />
	<elemento nombre = "flevorio" 	  simbolo="Fl"  numero="114" masa="287"        />
	<elemento nombre = "unumpentio"   simbolo="Uup" numero="115" masa="288"        />
	<elemento nombre = "livermorio"   simbolo="Lv"  numero="116" masa="293"        />
	<elemento nombre = "ununseptio"   simbolo="Uus" numero="117" masa="293"        />
	<elemento nombre = "ununoctio"    simbolo="Uuo" numero="118" masa="294"        />
</tabla>
